# numpy slicing 예제

In [1]:
import numpy as np

a = np.arange(10)
b = np.arange(4*4)

c = b.reshape(4,4)

In [7]:
import preprocessor as pr

ImportError: No module named 'data'

In [ ]:
create_question_vocab()

In [2]:
sl = slice(2, 7, 2) # start, end, step으로 구성, slice 객체가 따로 존재함
print(a[sl])

[2 4 6]


In [4]:
# 별도 Slice 객체를 생성하지 않고 []로 표기하여 처리
b = a[2:7:2] 
print(b)

[2 4 6]


In [9]:
print(c)
print(c.shape)
#print(c[2 :])
#print(c[2, :])  #  맨 앞은 row 수 그럼 나머지는 ??
#print(c[2, 0:]) #  예측해보라 2열의 리스트에 대해서 slicing하라는 의미임
print(c[:, -1])
print("====================")
print(c[:, None].shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
(4, 4)
[ 3  7 11 15]
(4, 1, 4)


In [ ]:
(4, 4, 4)
====================
(4, 1, 4, 4)